#!/bin/bash

source $HOME/.bashrc

export NAMESPACE=$(mktemp -d)
9p ls plumb/ >/dev/null 2>/dev/null || (cd /; 9 plumber) 

FONT=$PLAN9/font/fixed/unicode.9x18B.font
exec $HOME/apps/bin/acmeb -f $FONT -a $@
